version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=todo
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
  postgres:
    image: postgres:16.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=todo
    ports:
      - '5432:5432'
    volumes:
      - './migrations/init.sql:/docker-entrypoint-initdb.d/init.sql'